### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by imranbarbhuiya** [elbkr/ticket-bot#4]
I want to do the last task

- [ ] 5. Possibility to make the ticket names to ticket-ASCENDING_NUMBER
https://github.com/elbkr/ticket-bot/blob/97f51af779be4bcae49584e2af5f8cf7b699b0ba/todo#L5

Lmk if anyone have already started?

**Comment by elbkr** [comment]
Hi, no one did it yet. Thanks ^^

**Comment by imranbarbhuiya** [comment]
I'm a bit busy because of my college exam I'll try tomorrow.

Ig I only need to change here or anywhere else too?

https://github.com/elbkr/ticket-bot/blob/97f51af779be4bcae49584e2af5f8cf7b699b0ba/src/events/interactions/buttonPress.js#L34

**Comment by imranbarbhuiya** [comment]
Also what about using [winston](https://www.npmjs.com/package/winston) instead of chalk

**Comment by elbkr** [comment]
> I'm a bit busy because of my college exam I'll try tomorrow.
> 
> Ig I only need to change here or anywhere else too?
> 
> https://github.com/elbkr/ticket-bot/blob/97f51af779be4bcae49584e2af5f8cf7b699b0ba/src/events/interactions/buttonPress.js#L34

Yes, but you have to get the guild tickets count, and also make a command to set the type: ascending numbers or username

**Comment by elbkr** [comment]
> Also what about using [winston](https://www.npmjs.com/package/winston) instead of chalk

I’ll check it later

**Comment by imranbarbhuiya** [comment]
> > I'm a bit busy because of my college exam I'll try tomorrow.
> > Ig I only need to change here or anywhere else too?
> > https://github.com/elbkr/ticket-bot/blob/97f51af779be4bcae49584e2af5f8cf7b699b0ba/src/events/interactions/buttonPress.js#L34
> 
> Yes, but you have to get the guild tickets count, and also make a command to set the type: ascending numbers or username

Ok sure

> but you have to get the guild tickets count,

Will be doing it by checking only active tickets, or should I consider closed tickets also?

**Comment by elbkr** [comment]
Consider all tickets

**Comment by imranbarbhuiya** [comment]
If we consider all tickets then we need to save the current highest ticket number in database also if there is no active ticket channels all previous were closed then making a new channel named eg. Ticket-100 doesn't makes sense. I prefer considering only opened tickets but if u want me to consider all then np I'll do it. 

Need some time and due to clg and exam I'm not getting much time.

**Comment by elbkr** [comment]
No need to, we can just grt the current tickets count before creating the new doc and new ticket.

**Comment by elbkr** [comment]
> Also what about using [winston](https://www.npmjs.com/package/winston) instead of chalk

Winston is for logging, I use chalk for the text colors

**Comment by imranbarbhuiya** [comment]
> > Also what about using [winston](https://www.npmjs.com/package/winston) instead of chalk
> 
> Winston is for logging, I use chalk for the text colors

winston will do all by itself you just need to assign a color to respective log like

Logger.debug should show white
Logger.info blue like this
