### ISSUE TITLE
Database problems

### ISSUE THREAD

**Issue by VoltDevelopment** [elbkr/ticket-bot#7]
[23-12-2021 10:53:26]: [Database] Disconnected from the database!
[23-12-2021 10:53:26]: [Database] Unable to connect to the database!
Error: querySrv ENOTFOUND _mongodb._tcp.SkySupport.pjxpv.mongodb.net

Error: querySrv ENOTFOUND _mongodb._tcp.SkySupport.pjxpv.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (node:dns:213:19)
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: querySrv ENOTFOUND _mongodb._tcp.SkySupport.pjxpv.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (node:dns:213:19) {
  errno: undefined,
  code: 'ENOTFOUND',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.SkySupport.pjxpv.mongodb.net'
}

**Comment by elbkr** [comment]
make sure to allow access from anywhere in network acces, in mongoDB site

**Comment by elbkr** [comment]
or also make sure you are not using a public wifi

**Comment by VoltDevelopment** [comment]
still same problem and im using private wifi network
